/* parser generated by jison 0.4.2 */
var music = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"expressions":3,"<SCORE>":4,"clave":5,"notas":6,"line":7,"</SCORE>":8,"EOF":9,"CLAVE":10,"<NOTE>":11,"tiempo":12,"nota":13,"octava":14,"puntillo":15,"</NOTE>":16,"<DIVISIONLINE/>":17,"<TIME>":18,"NUMBER":19,"</TIME>":20,"<NAME>":21,"NOTA":22,"</NAME>":23,"<OCTAVE>":24,"</OCTAVE>":25,"<PUNTILLO/>":26,"$accept":0,"$end":1},
terminals_: {2:"error",4:"<SCORE>",8:"</SCORE>",9:"EOF",10:"CLAVE",11:"<NOTE>",16:"</NOTE>",17:"<DIVISIONLINE/>",18:"<TIME>",19:"NUMBER",20:"</TIME>",21:"<NAME>",22:"NOTA",23:"</NAME>",24:"<OCTAVE>",25:"</OCTAVE>",26:"<PUNTILLO/>"},
productions_: [0,[3,6],[5,1],[6,0],[6,8],[7,0],[7,1],[12,3],[13,3],[14,3],[15,1],[15,0]],
performAction: function anonymous(yytext,yyleng,yylineno,yy,yystate,$$,_$
/**/) {

var $0 = $$.length - 1;
switch (yystate) {
case 1: 
	  typeof console !== 'undefined' ? console.log($$[$0-5]) : print($$[$0-5]);
	
	this.$ = $$[$0-4];
	//dibujaElementos();
	return elementos;
	
break;
case 2:this.$ = $$[$0].toUpperCase();
		//alert("clave:" + this.$);
		elementos.push(hashClave(this.$));
break;
case 3:this.$ = {};
break;
case 4:
		var not = hashNota(new Note($$[$0-3], $$[$0-4], $$[$0-2], $$[$0-1]));
		elementos.push(not);
		/*if (Object.keys($$[$0-6]).length != 0){
			elementos.push($$[$0-6]);
		}*/
		this.$ = not;
		
break;
case 5:this.$ = {};
break;
case 6:this.$ = hashLine();
		elementos.push(this.$);
break;
case 7:this.$ = parseInt($$[$0-1]);
break;
case 8:
		this.$ = $$[$0-1];
		
break;
case 9:this.$ = parseInt($$[$0-1]);
break;
case 10:this.$ = true;
break;
case 11:this.$ = false;
break;
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:3,10:[1,4]},{6:5,8:[2,3],11:[2,3],17:[2,3]},{8:[2,2],11:[2,2],17:[2,2]},{7:6,8:[2,5],11:[2,5],17:[1,7]},{8:[1,8],11:[1,9]},{8:[2,6],11:[2,6]},{9:[1,10]},{12:11,18:[1,12]},{1:[2,1]},{13:13,21:[1,14]},{19:[1,15]},{14:16,24:[1,17]},{22:[1,18]},{20:[1,19]},{15:20,16:[2,11],26:[1,21]},{19:[1,22]},{23:[1,23]},{21:[2,7]},{16:[1,24]},{16:[2,10]},{25:[1,25]},{24:[2,8]},{8:[2,4],11:[2,4],17:[2,4]},{16:[2,9],26:[2,9]}],
defaultActions: {10:[2,1],19:[2,7],21:[2,10],23:[2,8]},
parseError: function parseError(str, hash) {
    throw new Error(str);
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = "", yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == "undefined")
        this.lexer.yylloc = {};
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === "function")
        this.parseError = this.yy.parseError;
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || 1;
        if (typeof token !== "number") {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == "undefined") {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
        if (typeof action === "undefined" || !action.length || !action[0]) {
            var errStr = "";
            if (!recovering) {
                expected = [];
                for (p in table[state])
                    if (this.terminals_[p] && p > 2) {
                        expected.push("'" + this.terminals_[p] + "'");
                    }
                if (this.lexer.showPosition) {
                    errStr = "Parse error on line " + (yylineno + 1) + ":\n" + this.lexer.showPosition() + "\nExpecting " + expected.join(", ") + ", got '" + (this.terminals_[symbol] || symbol) + "'";
                } else {
                    errStr = "Parse error on line " + (yylineno + 1) + ": Unexpected " + (symbol == 1?"end of input":"'" + (this.terminals_[symbol] || symbol) + "'");
                }
                this.parseError(errStr, {text: this.lexer.match, token: this.terminals_[symbol] || symbol, line: this.lexer.yylineno, loc: yyloc, expected: expected});
            }
        }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error("Parse Error: multiple actions possible at state: " + state + ", token: " + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0)
                    recovering--;
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {first_line: lstack[lstack.length - (len || 1)].first_line, last_line: lstack[lstack.length - 1].last_line, first_column: lstack[lstack.length - (len || 1)].first_column, last_column: lstack[lstack.length - 1].last_column};
            if (ranges) {
                yyval._$.range = [lstack[lstack.length - (len || 1)].range[0], lstack[lstack.length - 1].range[1]];
            }
            r = this.performAction.call(yyval, yytext, yyleng, yylineno, this.yy, action[1], vstack, lstack);
            if (typeof r !== "undefined") {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}
};

	
	//Notas:
	//var SMR = new InitSMR();
	var elementos = [];
	
	// Devuelve un objeto hash.
	var hashNota = function (valorNota){
		return {
			valor: valorNota,
			tipo: "nota"
		};	
	};
	var hashClave = function (valorClave){
		return {
			valor: valorClave,
			tipo: "clave"
		};
	};
	var hashLine = function (){
		return {
			tipo: "linea"
		}
	}

	/*function dibujaElementos(){
		for (var i in elementos){
			//alert("elemento: "+elementos[i].valor.duration);
			SMR.drawNote(elementos[i].valor);
		}
	}*/
	/*function Note (nota, duracion, octava){
		this.note = nota;
		this.duration = duracion;
		this.octave = octava;
	}*/

/* generated by jison-lex 0.1.0 */
var lexer = (function(){
var lexer = {
EOF:1,
parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },
setInput:function (input) {
        this._input = input;
        this._more = this._less = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {first_line:1,first_column:0,last_line:1,last_column:0};
        if (this.options.ranges) this.yylloc.range = [0,0];
        this.offset = 0;
        return this;
    },
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) this.yylloc.range[1]++;

        this._input = this._input.slice(1);
        return ch;
    },
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length-len-1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length-1);
        this.matched = this.matched.substr(0, this.matched.length-1);

        if (lines.length-1) this.yylineno -= lines.length-1;
        var r = this.yylloc.range;

        this.yylloc = {first_line: this.yylloc.first_line,
          last_line: this.yylineno+1,
          first_column: this.yylloc.first_column,
          last_column: lines ?
              (lines.length === oldLines.length ? this.yylloc.first_column : 0) + oldLines[oldLines.length - lines.length].length - lines[0].length:
              this.yylloc.first_column - len
          };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        return this;
    },
more:function () {
        this._more = true;
        return this;
    },
less:function (n) {
        this.unput(this.match.slice(n));
    },
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20)+(next.length > 20 ? '...':'')).replace(/\n/g, "");
    },
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c+"^";
    },
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) this.done = true;

        var token,
            match,
            tempMatch,
            index,
            col,
            lines;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i=0;i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (!this.options.flex) break;
            }
        }
        if (match) {
            lines = match[0].match(/(?:\r\n?|\n).*/g);
            if (lines) this.yylineno += lines.length;
            this.yylloc = {first_line: this.yylloc.last_line,
                           last_line: this.yylineno+1,
                           first_column: this.yylloc.last_column,
                           last_column: lines ? lines[lines.length-1].length-lines[lines.length-1].match(/\r?\n?/)[0].length : this.yylloc.last_column + match[0].length};
            this.yytext += match[0];
            this.match += match[0];
            this.matches = match;
            this.yyleng = this.yytext.length;
            if (this.options.ranges) {
                this.yylloc.range = [this.offset, this.offset += this.yyleng];
            }
            this._more = false;
            this._input = this._input.slice(match[0].length);
            this.matched += match[0];
            token = this.performAction.call(this, this.yy, this, rules[index],this.conditionStack[this.conditionStack.length-1]);
            if (this.done && this._input) this.done = false;
            if (token) return token;
            else return;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line '+(this.yylineno+1)+'. Unrecognized text.\n'+this.showPosition(),
                    {text: "", token: null, line: this.yylineno});
        }
    },
lex:function lex() {
        var r = this.next();
        if (typeof r !== 'undefined') {
            return r;
        } else {
            return this.lex();
        }
    },
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },
popState:function popState() {
        return this.conditionStack.pop();
    },
_currentRules:function _currentRules() {
        return this.conditions[this.conditionStack[this.conditionStack.length-1]].rules;
    },
topState:function () {
        return this.conditionStack[this.conditionStack.length-2];
    },
pushState:function begin(condition) {
        this.begin(condition);
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START
/**/) {

	var notas = {DO: 'DO', RE: 'RE', MI: 'MI', FA: 'FA', SOL: 'SOL', LA: 'LA', SI: 'SI'};
	var reserved_words = {SCORE: 'SCORE', NOTE: 'NOTE', TIME: 'TIME', OCTAVE: 'OCTAVE', E: 'E', DEF: 'DEF'};
	//var reserved_words = {SCORE: 'SCORE', NOTE: 'NOTE', TIME: 'TIME', OCTAVE: 'OCTAVE', E: 'E', DEF: 'DEF'};
	
	function idORrw (x) {	
	//return ((x.toUpperCase() in reserved_words)? x.toUpperCase() : 'ID');
	//return ((x.toUpperCase() in reserved_words)? x : 'ID');
		if (x.toUpperCase() in notas) {
			return 'NOTA';
		}
		if (x.toUpperCase() in reserved_words) {
			//return x.toUpperCase();
			return reserved_words[x.toUpperCase()];
		} 
		return 'ID';
	}

	function token (x) {
		x = x.toUpperCase();
		//if (x )
		return x;
	}
	

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 19
break;
case 2:return 10
break;
case 3:return 10
break;
case 4:return token(yy_.yytext)
break;
case 5:return ';'
break;
case 6:return idORrw(yy_.yytext)
break;
case 7:return yy_.yytext
break;
case 8:return 9
break;
case 9:return 'INVALID'
break;
}
},
rules: [/^(?:\s+)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:<ksol2\/>)/,/^(?:<KSOL2\/>)/,/^(?:<[/]?[a-zA-Z_]\w*[/]?>)/,/^(?:;)/,/^(?:\b[a-zA-Z_]\w*\b)/,/^(?:[-+*/^%()<>=!,{}])/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () { this.yy = {}; }Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();
if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = music;
exports.Parser = music.Parser;
exports.parse = function () { return music.parse.apply(music, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}